//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public int CateID { get; set; }
        public string Image { get; set; }
        public string NewPromotion { get; set; }
        public int Installment { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Detail { get; set; }
        public string Description { get; set; }
        public string Specification { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public double ProPrice { get; set; }
        public string MetaKey { get; set; }
        public string MetaDesc { get; set; }
        public int Status { get; set; }
        public System.DateTime Created_at { get; set; }
        public int Created_by { get; set; }
        public System.DateTime Updated_at { get; set; }
        public int Updated_by { get; set; }
        public Nullable<double> ProRate { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
